### ISSUE TITLE
Lyp lilypond not recognized

### ISSUE THREAD

**Issue by tunesmith** [frescobaldi/frescobaldi#1014]
Hi, on my mac with 2.2.0 I tried pointing to lyp's lilypond, which for me is located at `~/.rvm/gems/ruby-2.1.2@rails4.1/bin/lilypond`. Upon pressing submit, frescobaldi didn't recognize the path. It's possible it is because of that @ sign, which I need to backslash when I refer to it in the shell.  (I tried putting a backslash into the dialogue window but that didn't work either.)

**Comment by MichaelHendry** [comment]
Coming up against a similar problem (without the @ sign), I wonder how you resolved this?

**Comment by dliessi** [comment]
I installed lyp's LilyPond and it worked as expected, but it didn't have @ in the path.
So I added @ to the name of LilyPond's released app bundle and that worked as expected, too.

I'm closing this issue because it works for me: if it is still not working for you, please feel free to reopen the issue and we'll try to investigate further.
