### ISSUE TITLE
Crash in OS X El Capitan 10.11.6

### ISSUE THREAD

**Issue by DaviRaubach** [frescobaldi/frescobaldi#1294]
The last release of Frescobaldi crashes in my system.

[OSX 10.11.6 error.txt](https://github.com/frescobaldi/frescobaldi/files/4541461/OSX.10.11.6.error.txt)

Thank you!

**Comment by dliessi** [comment]
Unfortunately, that's currently expected (as noted in the [release page](https://github.com/frescobaldi/frescobaldi/releases/tag/v3.1.2)), since the application bundle was built on a later version of macOS.
I'm afraid at the moment your only way to run Frescobaldi 3 is MacPorts (see [the wiki](https://github.com/frescobaldi/frescobaldi/wiki/How-to-install-Frescobaldi-on-Mac-OS-X)).

(If you don't want to use MacPorts, you can choose to run [the latest version of Frescobaldi 2](https://github.com/frescobaldi/frescobaldi/releases/tag/v2.20.0), but beware that it likely won't get any other updates.)

**Comment by DaviRaubach** [comment]
I have updated to High Sierra a couple of days ago... Thank you.
