### ISSUE TITLE
Ghostscript error on Mac with 2.21.1

### ISSUE THREAD

**Issue by rpspringuel** [frescobaldi/frescobaldi#1305]
When using LilyPond 2.21.1 (installed by MacPorts) I get an GhostScript error when trying to typeset music in Frescobaldi:

```
warning: g_spawn_sync failed (0): gs: Failed to execute child process “gs” (No such file or directory)
```

The process completes successfully when LilyPond is invoked from the command-line and when I switch to LilyPond 2.20.0 (also installed by MacPorts).

Version Information:
Frescobaldi: 3.1.2
Extension API: 0.9.0
Python: 3.7.7
python-ly: 0.9.5
Qt: 5.14.1
PyQt: 5.14.1
sip: 4.19.21
poppler: 0.83.0
python-poppler-qt: 0.75.0
OS: Darwin-19.4.0-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by dliessi** [comment]
Reported also on LilyPond's user mailing list: https://lists.gnu.org/archive/html/lilypond-user/2020-05/msg00200.html

I can reproduce it with the prebuilt application bundle.
With MacPorts' Frescobaldi, instead, it works correctly.

I will investigate this.
Since you already have MacPorts on your machine, you can use its Frescobaldi in the meantime.
(Actually I think that you should prefer MacPorts' Frescobaldi, since it isn't affected by many bugs of the application bundle.)

**Comment by rpspringuel** [comment]
I tried installing the MacPorts Frescobaldi, but had problems with the poppler-qt5 prerequisite (https://trac.macports.org/ticket/60526) It wouldn’t extract properly and without it, of course, Frescobaldi won’t install.  Once the problem with poppler-qt5 is fixed, I will make the switch. 

✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️
Fr. Samuel, OSB
(R. Padraic Springuel)
St. Anselm’s Abbey 
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by marnen** [comment]
I just ran into the same thing with the [Mac application bundle](https://gitlab.com/marnen/lilypond-mac-builder) of LilyPond 2.21 that I maintain. In that case, it was a GhostScript version issue caused by the LilyPond wrapper script not setting `PATH` properly, so that Lily was trying to use the system GhostScript (of a different version than it was expecting). Perhaps a similar fix will work for you?

**Comment by dliessi** [comment]
@marnen Thanks for the pointer!
