### ISSUE TITLE
Frescobaldi with temp files can have propblem with relative paths

### ISSUE THREAD

**Issue by vpetzel** [frescobaldi/frescobaldi#1388]
When compiling an unsaved document that relies on content specified in relative paths this might fail to build. In think it would thus be sensible to add the regular working directory to the Lilypond include path in such cases.

E.g.: Use \epsfile #X 10 "somefile.eps"
This will fail on an unsaved document, due to somefile.eps missing in the temporary directory.

**Comment by lfm83** [comment]
This works for me, even with "../somefile.eps". Frescobaldi does add the current working directory to LilyPond's include path (via -I) when compiling in a temp dir.
That way, not only \include "../somefile.ily" works, but also \epsfile, since LilyPond's gulp_file_to_string (in lily-guile.cc) uses the global_path class which knows about the directories given via -I (see main.cc).
So: I cannot reproduce the issue you describe.

**Comment by vpetzel** [comment]
@lfm83 Are you sure it does? I tried on three different system with current release Frescobaldi 3.1.3 and with current master from git, but it simply fails to find the file on a unsaved document. Also the load path printed in the error message does not contain the working dir.

**Comment by lfm83** [comment]
That's strange.
I'm using a (maybe not-so-)current git master, and for other reasons I had patched it in ordner to dump the actual LilyPond call it uses to stdout.
If I open an existing LilyPond file in Frescobaldi and immediately hit ctrl+m, I get:
['/home/lukas/lilypond-versions/2.20.0/bin/lilypond', '-ddelete-intermediate-files', '-dpoint-and-click', '-I/home/lukas/oll-lib/', '--pdf', '/home/lukas/Dokumente/Musiktheorie/Heinichen/teil2/643a.ly']
If I change that file without saving and hit ctrl+m again, I get:
['/home/lukas/lilypond-versions/2.20.0/bin/lilypond', '-ddelete-intermediate-files', '-dpoint-and-click', '-I/home/lukas/Dokumente/Musiktheorie/Heinichen/teil2/', '-I/home/lukas/oll-lib/', '--pdf', '/tmp/frescobaldi-xdf4jc40/tmp5t37vk9k/643a.ly']

Looks fine to me; am I missing something?

**Comment by vpetzel** [comment]
Hm. I’ve patched a fresh git master frescobaldi so that it does the same, but I only get
['/usr/bin/lilypond', '-ddelete-intermediate-files', '-dpoint-and-click', '-I/disks/Fast_Storage/valentin/OLL/', '--pdf', '/tmp/t.ly']
for the saved file and
['/usr/bin/lilypond', '-ddelete-intermediate-files', '-dpoint-and-click', '-I/disks/Fast_Storage/valentin/OLL/', '--pdf', '/tmp/frescobaldi-8tcsxsjf/tmpu9oqos4s/t.ly']
for the unsaved file.

Could this be some sort of regression?

**Comment by lfm83** [comment]
At first I suspected that your chosen saved file location in /tmp/, of all things, might be the culprit, but ...

... the problem comes from

```
            if filename and self.lydocinfo().include_args():
                includepath.insert(0, os.path.dirname(filename))
``` 
in documentinfo.py: This makes sure that the file's own directory is appended to the include path list **only if** there are \include's in the LilyPond file.
Of course, this leads to problems in a file using \markup \epsfile but having no \include.
I don't see a reason for this extra condition: I think it wouldn't hurt to add the necessary include path unconditionally.

**Comment by lfm83** [comment]
I created a pull request - that's a first for me, so it may well be that I messed up completely:[
https://github.com/frescobaldi/frescobaldi/pull/1390](url)

**Comment by vpetzel** [comment]
Thank you very much for finding the root of the issue! Dropping that condition should pose no problem, I think.
