### ISSUE TITLE
Porting to PyQt6

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1407]
@wbsoft Will you port Frescobaldi codebase to PyQt6 *sooner or later*?
Just curious to know if you have any roadmap in mind.

https://www.riverbankcomputing.com/static/Docs/PyQt6/pyqt5_differences.html

**Comment by bmjcode** [comment]
I just posted on #1691, but since that one's closed I'll mention it here too. Qt 6 has added hyperlink support to its built-in PDF module via the [QPdfLinkModel](https://doc.qt.io/qt-6/qpdflinkmodel.html) class. If that covers our needs, that might let us drop python-poppler-qt5, which would both simplify the port and ease up a lot of the current packaging issues.

**Comment by bmjcode** [comment]
To follow up on my last comment, I've started on a Qt 6 port of qpageview using QtPdf as the rendering backend. Details here:

https://github.com/frescobaldi/qpageview/issues/17

**Comment by bmjcode** [comment]
And here's Frescobaldi itself running under Qt 6:

https://github.com/bmjcode/frescobaldi/tree/qt6

So far I have just enough working to load the main window and open a score. Most other features, including engraving, remain either untested or outright broken. But I don't think it's a bad start.

The biggest change I'm seeing from PyQt5 is that version 6 adds the enum type to all its constants' names, so for example you have to write `QEvent.Type.MouseButtonPress` instead of `QEvent.MouseButtonPress`. Fixing these probably accounts for 95% of what I've done so far. I think I've got the most obvious ones done, but there's plenty more of them left to do.

**Comment by fedelibre** [comment]
Fixed by #1780
