### ISSUE TITLE
Can’t display PDFs with Frescobaldi 3.3 Windows installer

### ISSUE THREAD

**Issue by jeanas** [frescobaldi/frescobaldi#1579]
According to [this mailing list thread](https://groups.google.com/g/frescobaldi/c/GApbmflqLlQ), the Frescobadi 3.3 installer for Windows produces a Frescobaldi application that displays blank pages when showing a PDF, although point-and-click links are present. I’m pretty sure this means python-poppler-qt5 was not properly packaged.

CC @19joho66

**Comment by Blankdoor** [comment]
I also have this issue.
Here is a screenshot of it not working
![image](https://user-images.githubusercontent.com/37357383/229703562-3f8eb879-a6c8-44a9-9ee4-cac931c3963b.png)

**Comment by fedelibre** [comment]
@Blankdoor Does it also happen if you save the file?

Did you have a previous version of Frescobaldi installed before installing 3.3.0?
I've just tried a fresh install on Windows and it didn't work. I'll open a new issue.

**Comment by 19joho66** [comment]
I needed to find a computer where I could do a fresh install to reproduce this issue as well as issue #1580. 
The problem here is, that the poppler version 21.03 produces blank pages. (The same thing happened some time earlier, where only version 0.80 worked and the versions 0.81 and 0.82 didn't.
I've build a poppler library base on poppler 20.12.1 which seems to work. I'll so some more testing an if everything looks good I'll provide a new setup.

**Comment by Blankdoor** [comment]
Hi @jeanas ,
I tried with the installer just now.
Yesterday was the first time I've ever run or installed this software. I am running windows 10.
I still see no rendering in the view window. But yes it does save the PDF correctly. See screenshots below.
![image](https://user-images.githubusercontent.com/37357383/229898370-41100506-706e-4767-b7b2-e3fab3ad74ec.png)
![image](https://user-images.githubusercontent.com/37357383/229898547-36867278-c0d8-4464-9836-9b257a4a5104.png)

**Comment by fedelibre** [comment]
The latest installer works fine! I can see the music preview.

@Blankdoor Please download the new installer and try again.
I'm closing this issue.
