### ISSUE TITLE
Update user guide: Compiling master document

### ISSUE THREAD

**Issue by jka-kan** [frescobaldi/frescobaldi#1801]
Section "LilyPond files that include other files" in [https://www.frescobaldi.org/uguide-1/running](https://www.frescobaldi.org/uguide-1/running) needs update. The soprano example has comment line "%%master: NewSong.ly".
Shouldn't this be "% -*- master: NewSong.ly" on newer versions?

**Comment by fedelibre** [comment]
The website is not up-to-date since a long time, unfortunately.

Please check the user manual within your installation (press F1) or look at the source files on GitHub. The updated manual page is [this one](https://github.com/frescobaldi/frescobaldi/blob/master/frescobaldi_app/userguide/docvars.md).
