### ISSUE TITLE
Autocomplete text using Google Gemini

### ISSUE THREAD

**Issue by ddugovic** [frescobaldi/frescobaldi#1817]
I appreciate the maintenance note and this is unlikely to happen anytime soon, however here's the concept:

Mimic the IntelliJ integration w/ GitHub Copilot experience, instead using Google Gemini to autocomplete text in a variety of different contexts.

**Comment by bmjcode** [comment]
For those of us who don't use IntelliJ, what specifically would this do that the existing autocomplete doesn't?

**Comment by ddugovic** [comment]
I agree that I need to clearly articulate the use case rather than just explaining this by way of analogy.  It's complex to explain the design of, but I'll work on this...

While it is true that Gemini powers Google Assistant and Search, it's more than just a chatbot.  One possible use case might be: I have a music recording which I am transcribing, and Gemini (processing the audio rercording) autocompletes notes and rhythms in the same voice.

**Comment by bmjcode** [comment]
> One possible use case might be: I have a music recording which I am transcribing, and Gemini (processing the audio rercording) autocompletes notes and rhythms in the same voice.

I think what you're asking is much bigger than Frescobaldi. Automatic transcription alone would be a pretty complex program in its own right. You should probably start with someone involved in AI or machine learning rather than us; if what you want is possible with current technology, then hooking it into our fancy text editor is almost certainly the least complicated part.

**Comment by jeanas** [comment]
Yeah, I agree that this seems out of scope for Frescobaldi. Also, you could always write it as an extension.
