### ISSUE TITLE
unfortunate shorcut for Macos

### ISSUE THREAD

**Issue by juanalexei** [frescobaldi/frescobaldi#22]
On mac Command-M is usually used for minimizing the window. Command-R (like Run) or Command-T (like Typeset) would be a better choice.

**Comment by wbsoft** [comment]
@dliessi , can this issue be closed?

**Comment by dliessi** [comment]
There is nothing to do for the first reported problem, unless you want to consider changing the LilyPond compile shortcut letter from M to T (on all platforms).
(For the record, I use both TeX with TeXworks or TeX Shop and LilyPond with Frescobaldi almost every day, both on Linux and on Mac, and I must say that often, instead of compiling the score with Command-M or Control-M, I open the snippet editor with Command-T or Control-T instead.)

I think we can close this issue.
I intend to revise the default shortcuts on Mac anyway, sooner or later, but the most annoying ones (#860) have been fixed.

**Comment by wbsoft** [comment]
Ok, thanks!
