### ISSUE TITLE
Do we have to change from QtWebkit to QtWebEngineWidgets?

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#919]
http://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5

indicates that QtWebkit is actually superseded by the newer package. And if it's deprecated it may disappear at some point. Also, better support for HTML and JavaScript seems interesting for me.

**Comment by 19joho66** [comment]
The QtWebKit has been resurrected for Qt5.8: [https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5](url). 

I've used this package for the windows 3.0.0 setup, because I couldnt use Qt5.6 due to SVG issues. I then tried Qt5.7 and used the QWebEngine bacuase QWebKit wasn't available for this version anymore. This did work in general, but you couldn't reload a SVG page because of a bug in the 5.7 WebEngine. I then went back to 5.6 with QWebEngine and this worked.
Then I found the WebKit for Qt5.8 and finally used that because then I could use the same code base used for Linux and Mac. (See issue #848)

I think the QtWebKit for Qt5.8 is not a official package of Qt so I'd suggest it would be preverable to change to QWebEngine for the future. This would mean that Qt5.8 would have to be used for all platforms.

**Comment by wbsoft** [comment]
Ok, it seems that it is necessary to move from QtWebKit to QtWebEngine?

The documentation browser and the SVG editor both use QtWebkit.

On my systems I still use Qt5.9, but the Frescobaldi 3.1 release should work with Qt5.13 of course.
So I will dive into this and see if I can convert both modules to QtWebEngine.

**Comment by wbsoft** [comment]
I ported the LilyPond documentation browser from QtWebKit to QtWebEngine.
The SVG editor/view is the other component, which is slightly more involved as the interaction with JavaScript has been changed. From what I've read, it will be no problem to support all functionality in QtWebEngine.

@PeterBjuhr , are you able to have a look at the SVG view? QWebView maps easily to QWebEngineView, and QWebPage maps to QWebEnginePage, but frame and javascript handling has changed. (More at https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html ) Maybe I succeed on my own, but you are more at home in this module I guess :-)

**Comment by 19joho66** [comment]
I've already ported to QtWebengine about a year ago and I've rebased it on master on my machine today. Looks like it works so far. I can display the notesheet in the svg view and do pointandclick from the noetsheet to the sourcecode works (but not the other way around) 
@wbsoft If you'd like to have a look at my solution, let me know how to get it to you. Maybe you could use it as a starter...

Cheers

**Comment by wbsoft** [comment]
Great! I'll look into it!

**Comment by wbsoft** [comment]
@19joho66 where can I find your QtWebEngine port? If you have a fork you can create a pull request, you can also email me a patch. (wbsoft@xs4all.nl)

**Comment by 19joho66** [comment]
I've just placed a pull request, but is somehow got a bit messed up. But since you've found the changes I think everything is fine so far.

**Comment by wbsoft** [comment]
Based on your PR I implemented the port slightly simpler and a bit more efficient. Thanks! QtWebEngine behaves different in dragging, that needs a fix. But the base is working.
