### ISSUE TITLE
signals.Signal vs. pyqtSignals

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#955]
Is there any reason why custom signals are partly implemented using `signals.Signal` and partly using PyQt's `pyqtSignal`?

If there is *not*, should all instances of one invocation be changed to the other?

**Comment by uliska** [comment]
@wbsoft I've come across this issue again recently. Can you share any insights on this? Or is it simply that while you *did* implement a custom module for signals some other places still use the standard PyQt class?

**Comment by wbsoft** [comment]
Only QObjects can have pyqtSignals. That's why I implemented the signals module; I don't want to create QObjects (except for QWidget descendants), but I like the signal/slot mechanism. A nice part in signals is that a connection does not keep a reference, and that a priority can be given, influencing the order in which connections are called.

**Comment by uliska** [comment]
Why don't you want to create QObjects? This is something I was wondering too recently.

I have now used QObjects in some places, mostly because of the parenting (right now for example I have a "Runner" object (which is the object that handles the execution of a Job within a JobQueue), and its parent will be either a specific JobQueue (e.g. "engrave" or "crawl") or the global job queue, depending on whether the runner is assigned to a queue as a dedicated runner or belongs to the pool of shared runners.

Of course such relationships can be implemented in "pure" Python too, but I thought that it is quite natural to use Qt's mechanisms for that, especially in the context of a Qt application anyway...
So do you have any advice or wishes or demands when to use `QObject` and when `object` as base classes?

**Comment by wbsoft** [comment]
There is no problem in inheriting from QObject if course, when it has nice advantages such as the ability to receive events etc, but in most cases I try to do as much as possible in pure Python without dependency on Qt, and separate core code and ui code as much as possible. It saves some overhead in conversion between python objects and wrapped c++/Qt objects too.

But in the job context, Qt is perfect I think, because of the event driven communication with subprocesses in QProcess, the signalling in QThread etc. In the background rendering jobs in qpopplerview and now qpageview I also use those.

**Comment by uliska** [comment]
OK, thanks for the clarification. I'll consider this in the future when having to decide which base class to use.
